import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { createRequire } from "module";

const require = createRequire(import.meta.url);
const sharp = require("sharp");

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..", "public");
const outDir = path.join(__dirname, "..", ".tmp-compress");

const jobs = [
  { file: "images/g-projects-logo.webp", width: 256, quality: 82 },
  { file: "images/hero.webp", width: 1920, quality: 80 },
  { file: "images/saloni.webp", width: 1800, quality: 80 },
  { file: "images/kouzina.webp", width: 1600, quality: 80 },
  { file: "images/krevati.webp", width: 1600, quality: 80 },
  { file: "images/kathistiko.webp", width: 1600, quality: 80 },
  { file: "images/ntoulapa.webp", width: 1600, quality: 80 },
  { file: "images/domatio.webp", width: 1600, quality: 80 },
  { file: "images/comparison/cad-plan.webp", width: 1600, quality: 80 },
  { file: "images/comparison/kitchen-cad-before.webp", width: 1600, quality: 80 },
];

fs.mkdirSync(outDir, { recursive: true });

async function compressOne(job) {
  const full = path.join(root, job.file);
  if (!fs.existsSync(full)) {
    console.log("skip missing:", job.file);
    return;
  }
  const before = fs.statSync(full).size;
  const tmp = path.join(outDir, job.file.replace(/[\\/]/g, "__"));
  await sharp(full)
    .rotate()
    .resize({
      width: job.width,
      height: job.width,
      fit: "inside",
      withoutEnlargement: true,
    })
    .webp({ quality: job.quality, effort: 4 })
    .toFile(tmp);

  const after = fs.statSync(tmp).size;
  if (after >= before * 0.98) {
    fs.unlinkSync(tmp);
    console.log(
      `keep  ${job.file} (${Math.round(before / 1024)}KB — already small)`
    );
    return;
  }

  const data = fs.readFileSync(tmp);
  fs.writeFileSync(full, data);
  fs.unlinkSync(tmp);
  console.log(
    `ok    ${job.file}: ${Math.round(before / 1024)}KB → ${Math.round(after / 1024)}KB`
  );
}

async function writeHeroBlur() {
  const hero = path.join(root, "images/hero.webp");
  if (!fs.existsSync(hero)) return null;
  const buf = await sharp(hero)
    .resize(12, 8, { fit: "cover" })
    .webp({ quality: 40 })
    .toBuffer();
  return `data:image/webp;base64,${buf.toString("base64")}`;
}

for (const job of jobs) {
  await compressOne(job);
}

const blur = await writeHeroBlur();
if (blur) {
  const out = path.join(__dirname, "..", "src", "data", "placeholders.ts");
  fs.writeFileSync(
    out,
    `/** Tiny LQIP for hero — generated by scripts/compress-images.mjs */\nexport const heroBlurDataURL = "${blur}";\n`
  );
  console.log("wrote src/data/placeholders.ts");
}

fs.rmSync(outDir, { recursive: true, force: true });
